### ISSUE TITLE
戰鬥報告失效

### ISSUE THREAD

**Issue by nightMORALS** [andychucs/conning_tower#337]
海域進擊、戰鬥預測完全消失，並且有時在編隊進行中也會觸發報錯。

報錯：
```json
{"error":"Null check operator used on a null value","stack":"#0      KancolleData.parseBattle (package:conning_tower/models/feature/kancolle/data.dart:473)\n#1      KancolleData.parse (package:conning_tower/models/feature/kancolle/data.dart:250)\n#2      KancolleData.parseWith (package:conning_tower/models/feature/kancolle/data.dart:537)\n#3      HomePageState.enableListener.<anonymous closure>.<anonymous closure> (package:conning_tower/pages/home.dart:226)\n#4      StateController.update (package:riverpod/src/state_controller.dart:32)\n#5      HomePageState.enableListener.<anonymous closure> (package:conning_tower/pages/home.dart:226)\n#6      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606)\n#7      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/element.dart:538)\n#8      ResultData.map (package:riverpod/src/result.dart:74)\n#9      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:535)\n#10     ProviderElementBase.setState (package:riverpod/src/framework/element.dart:158)\n#11     StateProviderElement.create.<anonymous closure> (package:riverpod/src/state_provider/base.dart:141)\n#12     StateNotifier.state= (package:state_notifier/state_notifier.dart:227)\n#13     StateController.state= (package:riverpod/src/state_controller.dart:15)\n#14     StateController.update (package:riverpod/src/state_controller.dart:32)\n#15     WebController._kancolleMessageHandle (package:conning_tower/providers/generatable/webview_provider.dart:352)\n#16     WebController.onWebviewCreate.<anonymous closure> (package:conning_tower/providers/generatable/webview_provider.dart:368)\n#17     IOSWebMessageListener._handleMethod (package:flutter_inappwebview_ios/src/web_message/web_message_listener.dart:83)\n#18     InternalChannelController.initMethodCallHandler.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:631)\n#19     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571)\n#20     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564)\n#21     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581)\n#22     _invoke2 (dart:ui/hooks.dart:344)\n#23     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)\n#24     _Channel.push (dart:ui/channel_buffers.dart:135)\n#25     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)\n#26     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750)\n#27     _dispatchPlatformMessage (dart:ui/hooks.dart:257)\n","source":"http://125.6.189.215/kcsapi/api_req_battle_midnight/sp_midnight","data":"{\"api_result\":1,\"api_result_msg\":\"\\u6210\\u529f\",\"api_data\":{\"api_deck_id\":1,\"api_formation\":[2,1,1],\"api_f_nowhps\":[81,32,48,30,48,30],\"api_f_maxhps\":[81,32,48,30,48,30],\"api_fParam\":[[99,0,63,93],[48,79,49,49],[70,59,56,70],[52,80,50,49],[70,59,48,70],[47,79,33,49]],\"api_ship_ke\":[1527,1527,1522,1518,1576,1576],\"api_ship_lv\":[1,1,1,1,1,1],\"api_e_nowhps\":[76,76,60,48,37,37],\"api_e_maxhps\":[76,76,60,48,37,37],\"api_eSlot\":[[1505,1506,1515,1525,-1],[1505,1506,1515,1525,-1],[1505,1506,1525,1525,-1],[1504,1525,-1,-1,-1],[1502,1545,1542,-1,-1],[1502,1545,1542,-1,-1]],\"api_eParam\":[[68,48,40,70],[68,48,40,70],[58,42,30,60],[30,40,20,30],[38,66,32,26],[38,66,32,26]],\"api_smoke_type\":0,\"api_balloon_cell\":0,\"api_atoll_cell\":0,\"api_n_support_flag\":0,\"api_touch_plane\":[102,-1],\"api_flare_pos\":[4,-1],\"api_hougeki\":{\"api_at_eflag\":[0,1,0,0,0,0,0],\"api_at_list\":[0,0,1,2,3,4,5],\"api_n_mother_list\":[0,0,0,0,0,0,0],\"api_df_list\":[[1,1],[4],[2,2],[3,-1,-1],[4,4],[0],[5,5]],\"api_si_list\":[[\"298\",\"298\"],[1505],[\"91\",\"91\"],[\"90\",\"90\",\"12\"],[\"3\",\"3\"],[\"6\"],[\"297\",\"297\"]],\"api_cl_list\":[[1,1],[0],[1,1],[1,-1,-1],[1,1],[0],[1,1]],\"api_sp_list\":[1,0,1,4,1,0,1],\"api_damage\":[[98,114],[0],[106,113],[248,-1,-1],[144,0],[0],[132,139]]}}}"}
```

**Comment by kunlunxue-1** [comment]
我这边也发生了这个问题
机型：ipad 8
系统环境：iPad OS 17.6.1
进入战斗后弹窗提示解析数据发生错误
是否由于昨晚更新后变更了api导致？
